spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${{ username }}:${{ password }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}
    username: postgres
    password: SLhyaTs4Yp5fH4xLxisH
    PGHOST: containers-us-west-46.railway.app
    PGPORT: 7972
    PGDATABASE: railway
    driverClassName: org.postgresql.Driver
  profiles:
    active: prod

server:
    port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
